---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
type: Opaque
data:
  mysql-root-password: "cGFzc3dvcmQ=" # base64 encoded password   - password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
data:
  mysqld.cnf: |
    [mysqld]
    pid-file = /var/run/mysqld/mysqld.pid
    #socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    bind-address = 0.0.0.0
    symbolic-links=0
