apiVersion: v1
kind: Endpoints
metadata:
  name: storageos-etcd
  labels:
    app: etcd
    cluster: storageos
subsets:
- addresses:
  - ip: 139.162.234.133
  - ip: 139.162.198.65
  - ip: 178.79.168.252
  ports:
  - name: client
    port: 2379
    protocol: TCP
