apiVersion: v1
kind: Endpoints
metadata:
  name: storageos-etcd
  namespace: etcd
  labels:
    app: etcd
    cluster: storageos
subsets:
- addresses:
  - ip: 10.1.10.216
  - ip: 10.1.10.217
  - ip: 10.1.10.218
  ports:
  - name: client
    port: 2379
    protocol: TCP
