apiVersion: v1
kind: Service
metadata:
  name: storageos-etcd
  namespace: etcd
  labels:
    app: etcd
    cluster: storageos
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  selector: null
