apiVersion: "storageos.com/v1alpha1"
kind: "StorageOSCluster"
metadata:
  name: "storageos"
spec:
  secretRefName: "storageos-api" # Reference from the Secret created in the previous step
  secretRefNamespace: "default"  # Namespace of the Secret
  images:
    nodeContainer: "storageos/node:1.1.1"
  csi:
    enable: true
  resources:
    requests:
      memory: "512Mi"
  nodeSelectorTerms:
    - matchExpressions:
      - key: "node-role.kubernetes.io/compute" 
        operator: In
        values:
        - ""

