apiVersion: "storageos.com/v1"
kind: StorageOSCluster
metadata:
  name: "storageos"
spec:
  secretRefName: "storageos-api" # Reference from the Secret created in the previous step
  secretRefNamespace: "default"  # Namespace of the Secret
  images:
    nodeContainer: "storageos/node:v2.1.0"
  kvBackend:
    address: 'storageos-etcd-client.etcd:2379' # Example address, change for your etcd endpoint
    backend: 'etcd'
  sharedDir: '/var/lib/kubelet/plugins/kubernetes.io~storageos' # Needed when Kubelet as a container
  k8sDistro: "dockeree"
  resources:
    requests:
      memory: "512Mi" # This is for testing environments. For production environments, we recommend 4GB of Memory and 1 CPU
  #nodeSelectorTerms:
    #- matchExpressions:
      #- key: "node-role.kubernetes.io/compute"  # According to the labels you defined in your nodes
        #operator: In
        #values:
        #- ""
