apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: wordpress
    tier: frontend
  ports:
    - port: 80
      name: web
