kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp-uploads
  labels:
    storageos.com/replicas: "1"
spec:
  storageClassName: "fast"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
