---
- name: Add member
  hosts: new_nodes
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Generate certs
      import_role:
        name: tls_cert
      when: tls.enabled

    - name: Add member
      import_role:
        name: add_member
